# Generated by Django 6.0.6 on 2026-07-06 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('hockey', 'Hockey'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('grad_year', models.SmallIntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('intended_major', models.CharField(blank=True, max_length=150)),
                ('highlight_url', models.URLField(blank=True)),
                ('interest_level', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
