# Generated by Django 6.0.6 on 2026-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteprofile",
            name="grad_year",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="athleteprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
