# Generated by Django 6.0.6 on 2026-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_savedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("social", "Social"), ("tryout", "Tryout")],
                default="social",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
