# Generated by Django 6.0.6 on 2026-07-08 01:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('hockey', 'Hockey'), ('basketball', 'Basketball'), ('soccer', 'Soccer')], max_length=20)),
                ('school_or_team', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('usports', 'USports'), ('bchl', 'BCHL'), ('ohl', 'OHL'), ('whl', 'WHL'), ('ajhl', 'AJHL'), ('sjhl', 'SJHL'), ('mjhl', 'MJHL'), ('cjfl', 'CJFL'), ('cpl', 'CPL'), ('njcaa', 'NJCAA'), ('open', 'Open')], max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
