# Generated by Django 6.0.6 on 2026-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
